name: txtinv
prefix: /playpen-storage/soumitri/env/anaconda3/envs/txtinv
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2024.2.2=py38h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=10.2.0=py38h5eee18b_0
  - pip=20.3.3=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_1
  - setuptools=68.2.2=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.9.0=py38h06a4308_1
  - urllib3=2.1.0=py38h06a4308_1
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.18.0
      - anyio==4.2.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - comm==0.2.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - diffusers==0.14.0
      - exceptiongroup==1.2.0
      - fastjsonschema==2.19.1
      - fonttools==4.48.1
      - fqdn==1.5.1
      - importlib-resources==6.1.1
      - ipykernel==6.29.2
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.0.12
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - loguru==0.7.0
      - matplotlib==3.7.4
      - mistune==3.0.2
      - mypy-extensions==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.16.0
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - networkx==3.1
      - notebook==7.0.8
      - notebook-shim==0.2.3
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.9.0.80
      - overrides==7.7.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - pexpect==4.9.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.0
      - prometheus-client==0.19.0
      - ptyprocess==0.7.0
      - pycparser==2.21
      - pyparsing==3.1.1
      - pyrallis==0.3.1
      - pyre-extensions==0.0.23
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.33.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.17.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - tornado==6.4
      - transformers==4.27.4
      - triton==2.2.0
      - types-python-dateutil==2.8.19.20240106
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.10
      - xformers==0.0.16
